services:
  # Database service for huus-web
  huus-web-db:
    image: postgres:15
    environment:
      POSTGRES_USER: huus
      POSTGRES_PASSWORD: huus
      POSTGRES_DB: huus
    volumes:
      - huus_web_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: always
    ports:
      - "5050:80" # Expose pgAdmin on port 5050
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@example.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin-servers.json:/pgadmin4/servers.json:ro
    depends_on:
      - huus-web-db
